---
################################################
#  GITHUB ACTION WORKFLOW NAME
################################################
name: "Create tag for normal release or hotfix"

################################################
#  GITHUB ACTION EVENT TRIGGER
################################################
on:
  workflow_dispatch:
    inputs:
      IS_HOTFIX:
        type: choice
        description: "Is a hotfix or not."
        required: true
        default: "false"
        options:
          - "false"
          - "true"
      HOTFIX_TAG:
        description: "Tag to calculate creation of hotfix."
        default: ""
      IS_MAJOR:
        type: choice
        description: "Is a major release?"
        required: true
        default: "false"
        options:
          - "false"
          - "true"
      IS_MINOR:
        type: choice
        description: "Is a minor release?"
        required: true
        default: "false"
        options:
          - "false"
          - "true"
      IS_PATCH:
        type: choice
        description: "Is a patch release?"
        required: true
        default: "false"
        options:
          - "false"
          - "true"

################################################
#  GITHUB ACTION JOB
################################################
jobs:
  create-tag:
    permissions: write-all
    timeout-minutes: 15
    runs-on: ubuntu-latest

################################################
#  GITHUB ACTIONS GLOBAL ENV VARIABLES  
################################################
    env:
      ENV: live
      STATUSREPORTS3Bucket: deployment-status.practera.com
      REGION: ap-southeast-2
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:

################################################
#  GITHUB REPO CHECKOUT 
################################################
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release/live # branch for release

################################################
#  AWS credentials setup
################################################
      - name: Get AWS Organization Number
        id: AWS_ORG
        run: |
          CENTRALIZED=$(echo $AWS_ACCOUNT_ID | jq -r .CENTRALIZED)
          echo "::add-mask::$CENTRALIZED"
          echo "CENTRALIZED=$CENTRALIZED" >> $GITHUB_OUTPUT
      - name: Configure AWS Credentials from Centralized account
        uses: ./.github/actions/aws-oidc
        with:
          role-to-assume: arn:aws:iam::${{ steps.AWS_ORG.outputs.CENTRALIZED }}:role/github-restricted-role-to-assume
          region: ${{ env.REGION }}

################################################
#  Download script from s3 bucket
################################################
      - name: Download script file
        run: |
          aws s3 cp s3://$STATUSREPORTS3Bucket/scripts/tag-releasev2.sh tag-releasev2.sh
          chmod +x ./tag-releasev2.sh

################################################
#  Run script to create tag
################################################
      - name: Run script
        run: |
          ./tag-releasev2.sh
        env:
          IS_HOTFIX: ${{ github.event.inputs.IS_HOTFIX }}
          HOTFIX_TAG: ${{ github.event.inputs.HOTFIX_TAG }}
          IS_MAJOR: ${{ github.event.inputs.IS_MAJOR }}
          IS_MINOR: ${{ github.event.inputs.IS_MINOR }}
          IS_PATCH: ${{ github.event.inputs.IS_PATCH }}
