name: Test

on:
  pull_request:
  push:
    branches: [trunk, main, release/live]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
        id: chrome
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - run: npm ci --legacy-peer-deps
      - name: Unit tests
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: npm test
